### ISSUE TITLE
Re-deploying a Node.js proxy

### ISSUE THREAD

**Issue by inovakov** [apigee/apigeetool-node#12]
We would like to use the agile approach of developing APIs. This means, we start small, with several features and then we constantly improve the API by adding more and more features.

In case of a Node.js base proxy, this means developing the API locally and repeatedly deploying it to Apigee. We use the `deploynodeapp` command of apigeetool. It is intended to be used for initial deployment. And this is actually our problem. If I deploy the Node.js app and add some Apigee policies to the proxy, next time I re-deploy the Node.js app, the policies get overwritten.

We need a way, how to repeatedly deploy a Node.js app without having to re-create all the policies we need. Or what is the proper way, how to do this?

I suppose I can use the `deployproxy` command, but first I need to zip all Node.js folders the way Apigee can consume them. Maybe there could be a parameter to the `deployproxy` command, which will make sure, that the ZIP files are created before the proxy is deployed.

**Comment by earth2marsh** [comment]
:+1: 

IMO this is a major issue with the tool… no way to redeploy your node.js changes without clobbering any policies that might sit in front of it. Until there's a better way to deploy node.js apps that doesn't shim them into a proxy, apigeetool should be smart enough to update just the node.js app assets in the proxy to which it is deployed.

**Comment by gsjurseth** [comment]
If you simply handle it as an entire proxy and deploy with deployproxy (and add the -U switch) then it will auto upload all of the modules with it. Then you don't need to zip them and the tool will take care of this for you.

Does this solve your issue?

**Comment by earth2marsh** [comment]
@gsjurseth I don't think the issue is with the modules, but rather that you cannot both deploy with apigeetool and configure policies via the proxy editor without them being clobbered the next time apigeetool is used.

**Comment by gsjurseth** [comment]
@earth2marsh right, you'd have to pull those policy changes back down via fetchproxy and then unzip.
