### ISSUE TITLE
Favor package.json over -m for start script

### ISSUE THREAD

**Issue by earth2marsh** [apigee/apigeetool-node#17]
package.json allows for defining the default start command ([reference](https://docs.npmjs.com/misc/scripts#default-values)). 
```
…
    "scripts": {
  	"start": "node app.js"
    }
…
```
Keep the -m for the CLI to declare (or override) the main script to start, but if the declaration is in the package.json, Edge (or apigeetool) should use it.

**Comment by inovakov** [comment]
What if the start script field contains something like:
```
"start": "NODE_ENV=production supervisor index.js"
```

It will make the parsing harder.
