### ISSUE TITLE
Invalid command getKVMMap 

### ISSUE THREAD

**Issue by Tibeno88** [apigee/apigeetool-node#198]
```sh
Cannot find module './commands/getKVMmap'
```

The command file is **getkvmmap.js** but with promiseSdk or main command is required **getKVMmap**

https://github.com/apigee/apigeetool-node/blob/master/lib/promisesdk.js#L236
https://github.com/apigee/apigeetool-node/blob/master/lib/promisesdk.js#L236

File : 
https://github.com/apigee/apigeetool-node/blob/master/lib/commands/getkvmmap.js

**Comment by apkulick** [comment]
This operation will not work on Linux until this is fixed

**Comment by DinoChiesa** [comment]
I think this is fixed now in 0.16.1.  Can you try please?

**Comment by DinoChiesa** [comment]
This is fixed in v0.16.1
