### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by yash3012** [apigee/apigeetool-node#199]
Here is the solution:

Open your command prompt  and uninstall angular/cli by using 
"npm uninstall -g angular-cli" command.

Remove node_modules directory and then clear the cache by using 
"npm cache clear --force" command.

Remove 
C:\Users\<username>\AppData\Roaming\npm\ 
you can remove the folder this way 
rmdir C:\Users\<username>\AppData\Roaming\npm\  /s
and
 C:\Users\<username>\AppData\Roaming\npm-cache.
you can remove the folder this way 
rmdir C:\Users\<username>\AppData\Roaming\npm-cache  /s 

Now try to install the angular/cli@latest by using npm install -g @angular/cli@latest command.

_Originally posted by @taherkhans in https://github.com/apigee/apigeetool-node/issues/190#issuecomment-672843098_

**Comment by whitlockjc** [comment]
For the love of all that is holy, can you please avoid posting issues in this project _(`apigeetool-node`)_ for things related to other projects _(`angular-cli` in this case)_.  As was mentioned numerous times in #190, this issue has nothing to do with `apigeetool-node`.
