### ISSUE TITLE
API Products created via apigeetool cause "Invalid API call as no apiproduct match found"

### ISSUE THREAD

**Issue by pards** [apigee/apigeetool-node#207]
API Products created via apigeetool intermittently fail and cause HTTP 401 errors with "Invalid API call as no apiproduct match found" when exercising the API.

The behaviour is inconsistent - it works sometimes and not others with no code changes between deployments.

To workaround the issue, we have to create the API Products manually via the UI which means we cannot fully automate Apigee releases in the deployment pipeline.

Google support refused our support request stating that apigeetool is a community product.

**Comment by DinoChiesa** [comment]
If the problem is intermittent, it most often means that there is a cache issue in the MP, and you need to wait to synchronize the cache. 

If you can provide a working reproduction, I'll look at it. 
I know this is old. Sorry!
