### ISSUE TITLE
JSZip 3.0 error introduced in latest version 0.15.2

### ISSUE THREAD

**Issue by SLigtvoet** [apigee/apigeetool-node#218]
With the latest version update, in which the package node-zip is replaced by jszip, an error is introduced with the deployproxy command (perhaps more but haven't checked):

` 
This method has been removed in JSZip 3.0, please check the upgrade guide.
at JSZip.generate
    at Object.module.exports.makeOneFileZip 
    at createApiProxy`

**Comment by cleisommais** [comment]
Hi, guys, is there someone looking to fix it?

**Comment by ilyas-shah** [comment]
Please plan a fix for this 🔴

**Comment by theganyo** [comment]
My apologies, someone will have to look into this issue. In the meantime, I've rolled back the `latest` tag in NPM to 0.15.1.

**Comment by DinoChiesa** [comment]
Hi, can you try 0.16.1 please?

**Comment by DinoChiesa** [comment]
this has been fixed in v0.16.1
