### ISSUE TITLE
zip files and managing revisions

### ISSUE THREAD

**Issue by srinandan** [apigee/apigeetool-node#22]
When deploying nodejs applications using apigeetool, all the folders are compressed (zipped) before they are deployed to Edge (the main script is not compressed). Generally speaking, I think it is a great idea when it comes to folders like node_modules. But the command compresses other folders also. for ex: when deploying an a127 project, it compresses the "controllers" folder. When this happens, I lose the ability to make the smallest of edits in Edge. Every edit made outside of Edge will result in a new revision. I wonder if it makes sense to have a file similar to a .npmignore that tells you what files/folders to not zip or perhaps only compress node_modules by default and leave everything else.

**Comment by inovakov** [comment]
+1

**Comment by prabhatjha** [comment]
I think simply compressing node_modules and leaving rest unzipped would solve lots of pain. We will get this in the next release.
