### ISSUE TITLE
Create new release to allow easy access to "updateKVMEntry" sub-command

### ISSUE THREAD

**Issue by RomanKreisel** [apigee/apigeetool-node#232]
Hi,
we're using apigeetool in our CI/CD-Chain and would like to use update some key/value map entry using the "new" (#226, #212) updateKVMEntry (instead of delete & add) to prevent not having any entry at some short point in time.

Unforunately it seems, this command ins't available in the apigeetool from npmjs.org, even though this change has been pushed to github ~10 months ago.

Would it be possible to create another release so this sub-command is also available?

**Comment by DinoChiesa** [comment]
I know this is a really old request, but finally got round to publishing the latest.
