### ISSUE TITLE
deploynodeapp uploads files sequentially

### ISSUE THREAD

**Issue by illicium** [apigee/apigeetool-node#29]
Code should be doing the right thing and doing async calls, but it seems that [opts.asyncLimit](https://github.com/apigee/apigeetool-node/blob/master/lib/commands/deploynodeapp.js#L437) is not being set correctly (or at all).

**Comment by theganyo** [comment]
Thanks for the report. I'll have to look into that, but it should be set to 4 by default here: https://github.com/apigee/apigeetool-node/blob/master/lib/defaults.js#L10

**Comment by illicium** [comment]
Looks like it's picking up the default value of 4, but it's still bottlenecked. Quick benchmark:

asyncLimit | time
-----------|----------------------------------------------------------
4          | ./deploy.sh  5.27s user 1.20s system 8% cpu 1:20.29 total
8          | ./deploy.sh  5.23s user 1.16s system 11% cpu 54.948 total
16         | ./deploy.sh  5.19s user 1.24s system 18% cpu 35.260 total
32         | ./deploy.sh  5.04s user 1.00s system 19% cpu 30.260 total
64         | ./deploy.sh  4.99s user 1.03s system 17% cpu 34.487 total
