### ISSUE TITLE
Please ignore devDependencies in deploynodeapp

### ISSUE THREAD

**Issue by tmarrs** [apigee/apigeetool-node#31]
I can't deploy on Apigee with my `package.json` "as is" with the `-R` option because the devDependencies that I use (e.g., gulp, etc.) are too large and exceeds the Proxy Bundle limit. As a workaround, I have to do the following:
- Do `npm install --production`
- Use the `-U` option

But this is still a defect. Please fix your deployment tool to use `npm install --production`. That way, you're just pulling in the `dependencies` from `package.json`, and everything works as expected.

**Comment by gbrail** [comment]
Fixing this requires a change to Apigee Edge, because that's where NPM runs when apigeetool asks it to. I opened issue APIRT-2452 to track the resolution of this within Apigee.

**Comment by tmarrs** [comment]
Thanks for opening this issue within Apigee. Please let us know if/when it's resolved.

**Comment by smolnikov** [comment]
@gbrail any updates here?

**Comment by whitlockjc** [comment]
I've got someone looking at this and will update when we know something.

**Comment by noahdietz** [comment]
We have a PR inflight on Apigee Edge for the necessary API changes, to make `--production` the default when running `npm install`, as well as #90 here that toggles this flag when you want to install the `devDependencies`. 

We will update this issue when the fixes are merged and released.

**Comment by noahdietz** [comment]
We are still waiting on API changes to release. When those changes are released, we will cut a new release of `apigeetool` to publish this fix/change.
