### ISSUE TITLE
apigeetool fetchproxy "-e" argument being used for org

### ISSUE THREAD

**Issue by jpposteuca** [apigee/apigeetool-node#41]
I just installed apigeetool, and so far all the functions have worked fine, except for "fetchproxy".  I just ran: 
apigeetool fetchproxy -o {org} -e {env} -u {email} -n {proxy} -r 1 -D

and I see:
...
Going to invoke "https://api.enterprise.apigee.com/v1/o/{env}/apis/{proxy}/revisions/1?format=bundle"
...

"-e" is being used for "-o" in the request.

**Comment by jpposteuca** [comment]
I just saw the same "-e" problem with the "delete" function.

**Comment by noahdietz** [comment]
The `--environment -e` option should not be used for either of those commands, they are not environment scoped.
