### ISSUE TITLE
--api alias -n broken

### ISSUE THREAD

**Issue by confuser** [apigee/apigeetool-node#54]
Throws `Invalid arguments: Error: Unknown argument`

Most likely caused by @DinoChiesa #37 as it's using the same alias

This caused our deployments to fail. We've had to work around this by using --api instead of -n.

Documentation is still showing -n as an alias of --api for `deploynodeapp`.

Can you please bump to a major version v1? This was a breaking change, but the version bump was done as a patch 

cc @theganyo @mukundha

**Comment by confuser** [comment]
@mukundha Can you at least acknowledge this? This is a backwards breaking change which has caused us significant delays updating our deployment jobs. I've opened a P2 with support, and will escalate if necessary.

**Comment by mukundha** [comment]
yes @confuser - this is a bug.
this PR would address the issue - https://github.com/apigee/apigeetool-node/pull/56, will merge after the tests

**Comment by confuser** [comment]
@mukundha  And when will the tests be available? ETA? It's been over a week now. Why did I have to raise a P2 with support for you to answer? You should have reverted the commit which caused this and released a new patch version to solve the issue temporarily for customers, until a fix for the breaking PR which you merged in, was completed. Really disappointed in how this has been handled.

**Comment by mukundha** [comment]
sorry for the mis-communication - we were tracking it here, the source for this issue - https://github.com/apigee/apigeetool-node/pull/37
you really shouldn't need to create a support ticket - but in this case, it was my bad, apologies

will check with dino and update the ETA here today

**Comment by mukundha** [comment]
we got the tests in and verified - will merge the fix today @confuser

**Comment by mukundha** [comment]
@confuser - this is now fixed with this - https://github.com/apigee/apigeetool-node/pull/60
v0.6.6 is published to npm
