### ISSUE TITLE
Deploy particular revison

### ISSUE THREAD

**Issue by dgarlitt** [apigee/apigeetool-node#65]
Is there a way to use apigeetool to deploy a particular revision of the app to an environment? I know how to use deploynodeapp to deploy to an environment, but I would like to propagate an existing revision of the app from test to prod. Is that possible using apigeetool?

**Comment by noahdietz** [comment]
That is not currently supported by `apigeetool` no. It would be a pretty simple addition, however, just calling the "deploy revision" API described [here](https://docs.apigee.com/api-services/content/deploy-api-proxies-using-management-api#deployingapiproxies). I can look into working on this.
