### ISSUE TITLE
Is there support for invoking Organization key/value maps API through Apigeetool? 

### ISSUE THREAD

**Issue by sapan-desai** [apigee/apigeetool-node#75]
Hi,

Does apigeetool support invoking Organization key/value maps APIs (Add, Get etc)?

Thanks.

**Comment by noahdietz** [comment]
No there is currently no support for KVM operations through apigeetool. If you would like to open an issue as a feature request with some specific asks, we'd be happy to take a look into the work. Thank you!

**Comment by noahdietz** [comment]
Excuse me, I need to correct myself. There are a few unexposed commands for KVM operations.
* creating a KVM map
* adding an entry to a map
* map deletion

**Comment by noahdietz** [comment]
But these commands are for Environment KVMs, not Organization. Sorry for all of the confusion.
