### ISSUE TITLE
deployexistingrevision needs to be removed from README

### ISSUE THREAD

**Issue by ssvaidyanathan** [apigee/apigeetool-node#97]
https://github.com/apigee/apigeetool-node/blob/master/README.md#deployexistingrevision needs to be removed from GitHub README unless this is some new feature added to the plugin. The same is not available in the npm docs

**Comment by noahdietz** [comment]
Nope, this is just an unreleased feature. The `README` you are referring to is on the `master` branch, which will not match the documentation presented on the `npm` registry. The docs on `npm` are the currently released version of the module.

**Comment by aish-kozhisherry** [comment]
Is there any plan to release this feature to deploy an existing revision?
